# Generated by Django 3.1 on 2020-09-23 11:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=100, null=True)),
                ('ho_address', models.TextField(blank=True, null=True)),
                ('plant_address', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=30, null=True)),
                ('country', models.CharField(blank=True, max_length=25, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_person1_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_person2_name', models.CharField(blank=True, max_length=40, null=True)),
                ('contact_person1_number', models.CharField(blank=True, max_length=12, null=True)),
                ('contact_person2_number', models.CharField(blank=True, max_length=12, null=True)),
                ('date_of_signing', models.DateField(blank=True, null=True)),
                ('fees', models.IntegerField(blank=True, null=True)),
                ('replacement_perod', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_term', models.CharField(blank=True, max_length=30, null=True)),
                ('validity_of_resume', models.CharField(blank=True, max_length=30, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=40, null=True)),
                ('current_status', models.CharField(blank=True, max_length=20, null=True)),
                ('agreement1', models.FileField(blank=True, null=True, upload_to='')),
                ('agreement2', models.FileField(blank=True, null=True, upload_to='')),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
