# Generated by Django 3.1 on 2020-09-23 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20200923_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='agreement1',
            field=models.FileField(blank=True, null=True, upload_to='company_agreement'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agreement2',
            field=models.FileField(blank=True, null=True, upload_to='other_agreement'),
        ),
    ]
