# Generated by Django 3.1 on 2020-09-25 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20200923_1732'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='replacement_perod',
            new_name='replacement_period',
        ),
    ]
