# Generated by Django 3.1 on 2020-12-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0002_auto_20201223_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='email_id',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
